config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
get    'okashis/candy'          => 'okashis#candy'
get    'okashis/cake'          => 'okashis#cake'
get    'okashis/bis'          => 'okashis#bis'
get    'okashis/choco'          => 'okashis#choco'
get    'okashis/gam'          => 'okashis#gam'
get    'okashis/snack'          => 'okashis#snack'
  resources :users, only: [:show] # ユーザーマイページへのルーティング
  resources :okashis do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
end

root 'okashis#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :okashi
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :okashi
  belongs_to :user
  validates_uniqueness_of :okashi_id, scope: :user_id
end

app/models/okashi.rb
class Okashi < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :comments, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :okashi_tag_relations, dependent: :destroy
#tweetsテーブルから中間テーブルを介してTagsテーブルへの関連付け
  has_many :tags, through: :okashi_tag_relations, dependent: :destroy
end

app/models/okashi_tag_relation.rb
class OkashiTagRelation < ApplicationRecord
  belongs_to :okashi
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :okashi_tag_relations, dependent: :destroy
  #Tagsテーブルから中間テーブルを介してArticleテーブルへの関連付け
  has_many :okashis, through: :okashi_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :okashis, dependent: :destroy
         has_many :likes, dependent: :destroy
         mount_uploader :image, ImageUploader
  has_many :liked_okashis, through: :likes, source: :okashi
  has_many :comments, dependent: :destroy
  validates :name, presence: true #追記
  validates :profile, length: { maximum: 200 } #追記
  def already_liked?(okashi)
    self.likes.exists?(okashi_id: okashi.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      okashi = Okashi.find(params[:okashi_id])
      comment = okashi.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      end
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
      end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(okashi_id: params[:okashi_id])
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(okashi_id: params[:okashi_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/okashis_controller.rb
class OkashisController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
    def index
        @okashis = Okashi.all
        @rank_okashis = Okashi.all.sort {|a,b| b.liked_users.count <=> a.liked_users.count}
    end
    def new
        @okashi = Okashi.new
      end
    
      def create
        okashi = Okashi.new(okashi_params)
        okashi.user_id = current_user.id 
        if okashi.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
      def show
        @okashi = Okashi.find(params[:id])
        @comments = @okashi.comments
        @comment = Comment.new
      end
      def edit
        @okashi = Okashi.find(params[:id])
      end
      def update
        okashi= Okashi.find(params[:id])
        if okashi.update(okashi_params)
          redirect_to :action => "show", :id => okashi.id
        else
          redirect_to :action => "new"
        end
      end
      def destroy
        okashi = Okashi.find(params[:id])
        okashi.destroy
        redirect_to action: :index
      end

      def bis
        @okashis=Okashi.where(genre: "ビスケット")
      end
      def cake
        @okashis=Okashi.where(genre: "ケーキ")
      end
      def candy
        @okashis=Okashi.where(genre: "キャンデー")
      end
      def choco
        @okashis=Okashi.where(genre: "チョコレート")
      end
      def gam
        @okashis=Okashi.where(genre: "ガム、グミ")
      end
      def snack
        @okashis=Okashi.where(genre: "スナック")
      end
      private
      def okashi_params
        params.require(:okashi).permit(:name, :genre, :kansou, :item, :place, :company,:image, tag_ids: [])
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/okashis_helper.rb
module OkashisHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>おかシェア</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/7c6e29e4ba.js"  crossorigin="anonymous"></script> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Yomogi&display=swap" rel="stylesheet">

  </head>

  <body>
    <header>
      <h1>おかシェア</h1>
      <div class="header-list">
      <ul>
        <li><%= link_to "ホーム", okashis_path %></li>
        <li><%= link_to "新規投稿", new_okashi_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to "マイページ", user_path(current_user.id) %></li>
        <% else %>
        <% end %>
      </ul>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
    <p>Copyright © GeekSalon All Rights Reserved.</p>
  </footer>
</body>
</html>
  

app/views/okashis/bis.html.erb
<% @okashis.each do |t| %>
    <div class="okashi">
    <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <%= image_tag t.user.image_url, size: "250x200" if t.user.image? %>
    
      <%= t.name %>
 
      <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= link_to okashi_like_path(id: t.id, okashi_id: t.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= link_to okashi_likes_path(id: t.id, okashi_id: t.id), method: :post do %>
            <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% end %>
  <% else %>
  <i class="far fa-heart"></i><%= t.likes.count %>
  <% end %>
      <%= link_to "詳細へ", okashi_path(t.id) %> 
      <%= link_to "編集する", edit_okashi_path(t.id) %>
      <%= button_to "削除する", okashi_path(t.id), method: :delete %>
    </div>
  <% end %>

app/views/okashis/cake.html.erb
<% @okashis.each do |t| %>
    <div class="okashi">
    <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <%= image_tag t.user.image_url, size: "250x200" if t.user.image? %>
    
      <%= t.name %>
    
      <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= link_to okashi_like_path(id: t.id, okashi_id: t.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= link_to okashi_likes_path(id: t.id, okashi_id: t.id), method: :post do %>
            <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% end %>
  <% else %>
  <i class="far fa-heart"></i><%= t.likes.count %>
  <% end %>
      <%= link_to "詳細へ", okashi_path(t.id) %> 
      <%= link_to "編集する", edit_okashi_path(t.id) %>
      <%= button_to "削除する", okashi_path(t.id), method: :delete %>
    </div>
  <% end %>

app/views/okashis/candy.html.erb
<% @okashis.each do |t| %>
    <div class="okashi">
    <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <%= image_tag t.user.image_url, size: "250x200" if t.user.image? %>
   
      <%= t.name %>

      <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= link_to okashi_like_path(id: t.id, okashi_id: t.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= link_to okashi_likes_path(id: t.id, okashi_id: t.id), method: :post do %>
            <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% end %>
  <% else %>
  <i class="far fa-heart"></i><%= t.likes.count %>
  <% end %>
      <%= link_to "詳細へ", okashi_path(t.id) %> 
      <%= link_to "編集する", edit_okashi_path(t.id) %>
      <%= button_to "削除する", okashi_path(t.id), method: :delete %>
    </div>
  <% end %>

app/views/okashis/choco.html.erb
<% @okashis.each do |t| %>
    <div class="okashi">
    <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <%= image_tag t.user.image_url, size: "250x200" if t.user.image? %>
    
      <%= t.name %>
      <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= link_to okashi_like_path(id: t.id, okashi_id: t.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= link_to okashi_likes_path(id: t.id, okashi_id: t.id), method: :post do %>
            <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% end %>
  <% else %>
  <i class="far fa-heart"></i><%= t.likes.count %>
  <% end %>
      <%= link_to "詳細へ", okashi_path(t.id) %> 
      <%= link_to "編集する", edit_okashi_path(t.id) %>
      <%= button_to "削除する", okashi_path(t.id), method: :delete %>
    </div>
  <% end %>

app/views/okashis/edit.html.erb
<%= form_for @okashi do |f| %>


    <div class="field">
      <%= f.label :お菓子の名前 %>
      <%= f.text_field :name, :size => 10 %>
    </div>
  
    <div class="field">
      <%= f.label :ジャンル  %>
      <%= f.select :genre, 
      [["キャンデー", "キャンデー"], 
      ["チョコレート", "チョコレート"], 
      ["ガム、グミ,", "ガム、グミ"], 
      ["ビスケット", "ビスケット"], 
      ["ケーキ", "ケーキ"], 
      ["スナック", "スナック"]], include_blank: "選択して下さい" %>
    </div>
  
  
    <div class="field">
      <%= f.label :個数  %>
      <%= f.number_field :item, :size => 10 %>
    </div>
    <div class="field">
    <%= f.label :購入場所 %>
    <%= f.text_field :place, :size => 10 %>
  
  <div class="field">
  <%= f.label :会社名 %>
  <%= f.text_field :company, :size => 10 %>
  </div>
  
    <div class="field">
      <%= f.label :感想  %>
      <%= f.text_area :kansou, :size => "30x2" %>
    </div>
    <%= f.submit "投稿する" %>
  <% end %>

app/views/okashis/gam.html.erb
<% @okashis.each do |t| %>
    <div class="okashi">
    <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <%= image_tag t.user.image_url, size: "250x200" if t.user.image? %>
    
      <%= t.name %>
   
      <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= link_to okashi_like_path(id: t.id, okashi_id: t.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= link_to okashi_likes_path(id: t.id, okashi_id: t.id), method: :post do %>
            <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% end %>
  <% else %>
  <i class="far fa-heart"></i><%= t.likes.count %>
  <% end %>
      <%= link_to "詳細へ", okashi_path(t.id) %> 
      <%= link_to "編集する", edit_okashi_path(t.id) %>
      <%= button_to "削除する", okashi_path(t.id), method: :delete %>
    </div>
  <% end %>

app/views/okashis/index.html.erb
<div class="okashis-container">
<div style="text-align: center">
<%= image_tag 'aa.jpg', class:'photo' %>
</div>
<div class="zyanru">
ジャンル
</div>
<div class="genre">
<br><%= link_to "キャンディー", okashis_candy_path %>
<br><%= link_to "ケーキ", okashis_cake_path %>
<br><%= link_to "チョコレート", okashis_choco_path %>
<br><%= link_to "ガム、グミ", okashis_gam_path %>
<br><%= link_to "スナック", okashis_snack_path %>
<br><%= link_to "ビスケット", okashis_bis_path %>
</div>
<div class="about">
このサイトについて
</div>
<div class="coment">
いつも同じお菓子食べていませんか？
<br>
そんな人に使ってもらいたい、感想投稿サイト。
<br>
美味しいお菓子あったら、ぜひ共有してください！
<br>
一緒にお菓子の冒険しましょう！
</div>
  <% @rank_okashis.each do |t| %>
    <% end %>
</div>

app/views/okashis/new.html.erb
<div class=”tweets-container”>
<h3>新規投稿ページ</h3>
</div>

<%= form_for @okashi do |f| %>

  <div class="a">
  <div class="field">
    <%= f.label :お菓子の名前 %>
    <%= f.text_field :name, :size => 10 %>
  </div>
  <div class="field">
  <%= f.label :写真 %>
  <%= f.file_field :image %>
</div>
  <div class="field">
    <%= f.label :ジャンル  %>
    <%= f.select :genre, 
    [["キャンデー", "キャンデー"], 
    ["チョコレート", "チョコレート"], 
    ["ガム、グミ", "ガム、グミ"], 
    ["ビスケット", "ビスケット"], 
    ["ケーキ", "ケーキ"], 
    ["スナック", "スナック"]], include_blank: "選択して下さい" %>
  </div>


  <div class="field">
    <%= f.label :個数  %>
    <%= f.number_field :item, :size => 10 %>
  </div>
  <div class="field">
  <%= f.label :購入場所 %>
  <%= f.text_field :place, :size => 10 %>
</div>
<div class="field">
<%= f.label :会社名 %>
<%= f.text_field :company, :size => 10 %>
</div>

  <div class="field">
    <%= f.label :感想  %>
    <%= f.text_area :kansou, :size => "30x2" %>
  </div>
 
  <%= f.submit "投稿する" %>
<% end %>
<br>
<%= link_to "一覧に戻る", okashis_path %>
</div>

app/views/okashis/show.html.erb
<h3>投稿の詳細</h3>
<div class="okashi">
  
  <p><%= @okashi.name %></p>
  <br>
  <p><%= @okashi.genre %></p>
  <br>
  <p><%= @okashi.item %></p>
  <br>
  <p><%= @okashi.place %></p>
  <br>
  <p><%= @okashi.company %></p>
  <br>
  <br>
  <div class="b">
  <p><%= @okashi.kansou %></p>
  </div>
  <p><%= @okashi.created_at %></p>
    <% if user_signed_in? %>
      <% if current_user.already_liked?(@okashi) %>
        <%= link_to okashi_like_path(@okashi), method: :delete do %>
          <i class="fa-heart"></i><%= @okashi.likes.count %>
          <p>いいねを取り消す</p><%= @okashi.likes.count %>
        <% end %>
      <% else %>
        <%= link_to okashi_likes_path(@okashi), method: :post do %>
          <i class="far fa-heart"></i><%= @okashi.likes.count %>
          <p>いいね</p><%= @okashi.likes.count %>
        <% end %>
      <% end %>
    <% else %>
    <i class="far fa-heart"></i><%= @okashi.likes.count %>
      <p>いいねの数 = </p><%= @okashi.likes.count %>
    <% end %>
  <%= link_to "編集する", edit_okashi_path(@okashi.id) %>
  
 
</div>

<h2>いいねしたユーザー</h2>
<% @okashi.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>
<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@okashi, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>
<%= link_to "Tweet一覧に戻る", okashis_path %>

app/views/okashis/snack.html.erb
<% @okashis.each do |t| %>
    <div class="okashi">
    <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <%= image_tag t.user.image_url, size: "250x200" if t.user.image? %>
   
      <%= t.name %>
      <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= link_to okashi_like_path(id: t.id, okashi_id: t.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= link_to okashi_likes_path(id: t.id, okashi_id: t.id), method: :post do %>
            <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% end %>
  <% else %>
  <i class="far fa-heart"></i><%= t.likes.count %>
  <% end %>
      <%= link_to "詳細へ", okashi_path(t.id) %> 
      <%= link_to "編集する", edit_okashi_path(t.id) %>
      <%= button_to "削除する", okashi_path(t.id), method: :delete %>
    </div>
  <% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>登録情報</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.okashis.each do |t| %>
  <%= t.user.name %>
  <br>
  <%= t.name %>
  <br>
  <%= t.genre %>
  <br>
  <%= t.kansou %>
  <br>
  <%= t.item %>
  <br>
  <%= t.place %>
  <br>
  <%= t.company %>
<% end %>

<!-- 以下はいいね機能を実装している場合-->




<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_okashis.each do |t| %>
  <%= t.user.name %>
  <%= t.body %>
<% end %>
<!-- ここまで-->
<%= image_tag @user.image_url, size: "250x200" if @user.image? %>
<%= link_to "ホームに戻る", okashis_path %>